apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-nginx
  labels:
    app: python-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-nginx
  template:
    metadata:
      labels:
        app: python-nginx
    spec:
      containers:
      - name: nginx
        image: <DOCKER_USERNAME>/python-nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-nginx
spec:
  type: LoadBalancer
  selector:
    app: python-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
